services:
  redis:
    image: docker.io/redis
    ports: 6379:6379

  postgres:
    image: docker.io/postgres
    ports: 5432:5432
    volumes:
      - /media/son-of-satan/hoard/srv/service:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=eWU3vK%3H3hF45$^
