# Generated by Django 4.2.1 on 2023-06-01 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="task_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="owner_id",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="task_result",
            new_name="result",
        ),
    ]
